[package]
name = "compiladores_final"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.4.1"
pest_derive = "2.4.1"
